# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/AndroidApps/Flick/UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(842, 603))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.TabControls = QtWidgets.QWidget()
        self.TabControls.setObjectName("TabControls")
        self.tabWidget.addTab(self.TabControls, "")
        self.TabVA = QtWidgets.QWidget()
        self.TabVA.setObjectName("TabVA")
        self.TalkButton = QtWidgets.QPushButton(self.TabVA)
        self.TalkButton.setGeometry(QtCore.QRect(350, 80, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.TalkButton.setFont(font)
        self.TalkButton.setObjectName("TalkButton")
        self.VoiceLabel = QtWidgets.QLabel(self.TabVA)
        self.VoiceLabel.setGeometry(QtCore.QRect(0, 180, 831, 111))
        self.VoiceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.VoiceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VoiceLabel.setObjectName("VoiceLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.TabVA)
        self.scrollArea.setGeometry(QtCore.QRect(10, 290, 801, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setGeometry(QtCore.QRect(100, 40, 151, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_6.setObjectName("label_6")
        self.progressBar_2 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_2.setGeometry(QtCore.QRect(100, 70, 151, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_3.setGeometry(QtCore.QRect(100, 100, 151, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_5 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_5.setGeometry(QtCore.QRect(100, 130, 151, 23))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 811, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(780, 0, 20, 251))
        self.verticalScrollBar.setTracking(True)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.TabVA, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabControls), _translate("MainWindow", "Controls"))
        self.TalkButton.setText(_translate("MainWindow", "Talk"))
        self.VoiceLabel.setText(_translate("MainWindow", "Hi! I\'m your virtual assistant."))
        self.label_2.setText(_translate("MainWindow", "Google News"))
        self.label_3.setText(_translate("MainWindow", "YouTube"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.label_6.setText(_translate("MainWindow", "Reminder"))
        self.label_4.setText(_translate("MainWindow", "Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabVA), _translate("MainWindow", "Virtual Assistant"))

