# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/AndroidApps/Flick/UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(842, 603))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.TabGestures = QtWidgets.QWidget()
        self.TabGestures.setObjectName("TabGestures")
        self.label = QtWidgets.QLabel(self.TabGestures)
        self.label.setGeometry(QtCore.QRect(570, 0, 181, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.CaptureGestureButton = QtWidgets.QPushButton(self.TabGestures)
        self.CaptureGestureButton.setGeometry(QtCore.QRect(680, 100, 75, 23))
        self.CaptureGestureButton.setObjectName("CaptureGestureButton")
        self.FunctionDropdown = QtWidgets.QComboBox(self.TabGestures)
        self.FunctionDropdown.setGeometry(QtCore.QRect(560, 230, 231, 22))
        self.FunctionDropdown.setObjectName("FunctionDropdown")
        self.ReadGestureButton = QtWidgets.QPushButton(self.TabGestures)
        self.ReadGestureButton.setGeometry(QtCore.QRect(560, 100, 75, 23))
        self.ReadGestureButton.setObjectName("ReadGestureButton")
        self.GestureName = QtWidgets.QLineEdit(self.TabGestures)
        self.GestureName.setGeometry(QtCore.QRect(562, 60, 191, 20))
        self.GestureName.setObjectName("GestureName")
        self.label_7 = QtWidgets.QLabel(self.TabGestures)
        self.label_7.setGeometry(QtCore.QRect(560, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.AddButton = QtWidgets.QPushButton(self.TabGestures)
        self.AddButton.setGeometry(QtCore.QRect(560, 280, 75, 23))
        self.AddButton.setObjectName("AddButton")
        self.SaveButton = QtWidgets.QPushButton(self.TabGestures)
        self.SaveButton.setGeometry(QtCore.QRect(720, 280, 75, 23))
        self.SaveButton.setObjectName("SaveButton")
        self.label_8 = QtWidgets.QLabel(self.TabGestures)
        self.label_8.setGeometry(QtCore.QRect(560, 260, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ClearButton = QtWidgets.QPushButton(self.TabGestures)
        self.ClearButton.setGeometry(QtCore.QRect(640, 280, 75, 23))
        self.ClearButton.setObjectName("ClearButton")
        self.label_9 = QtWidgets.QLabel(self.TabGestures)
        self.label_9.setGeometry(QtCore.QRect(560, 140, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.StatusLabel = QtWidgets.QLabel(self.TabGestures)
        self.StatusLabel.setGeometry(QtCore.QRect(610, 140, 47, 13))
        self.StatusLabel.setObjectName("StatusLabel")
        self.ComboLabel = QtWidgets.QLabel(self.TabGestures)
        self.ComboLabel.setGeometry(QtCore.QRect(610, 260, 47, 13))
        self.ComboLabel.setObjectName("ComboLabel")
        self.label_10 = QtWidgets.QLabel(self.TabGestures)
        self.label_10.setGeometry(QtCore.QRect(180, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.dbTable = QtWidgets.QTreeWidget(self.TabGestures)
        self.dbTable.setGeometry(QtCore.QRect(10, 50, 531, 251))
        self.dbTable.setObjectName("dbTable")
        self.dbTable.headerItem().setText(0, "1")
        self.tabWidget.addTab(self.TabGestures, "")
        self.TabVA = QtWidgets.QWidget()
        self.TabVA.setObjectName("TabVA")
        self.TalkButton = QtWidgets.QPushButton(self.TabVA)
        self.TalkButton.setGeometry(QtCore.QRect(330, 80, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.TalkButton.setFont(font)
        self.TalkButton.setObjectName("TalkButton")
        self.VoiceLabel = QtWidgets.QLabel(self.TabVA)
        self.VoiceLabel.setGeometry(QtCore.QRect(0, 180, 811, 111))
        self.VoiceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.VoiceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VoiceLabel.setObjectName("VoiceLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.TabVA)
        self.scrollArea.setGeometry(QtCore.QRect(10, 290, 801, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setGeometry(QtCore.QRect(100, 40, 151, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_6.setObjectName("label_6")
        self.progressBar_2 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_2.setGeometry(QtCore.QRect(100, 70, 151, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_3.setGeometry(QtCore.QRect(100, 100, 151, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_5 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_5.setGeometry(QtCore.QRect(100, 130, 151, 23))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 811, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(780, 0, 20, 251))
        self.verticalScrollBar.setTracking(True)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 71, 21))
        self.label_12.setObjectName("label_12")
        self.progressBar_6 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_6.setGeometry(QtCore.QRect(100, 160, 151, 23))
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_7.setGeometry(QtCore.QRect(100, 190, 151, 23))
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setObjectName("progressBar_7")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.TabVA, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flick - Control Panel"))
        self.label.setText(_translate("MainWindow", "Add New Gesture"))
        self.CaptureGestureButton.setText(_translate("MainWindow", "Capture"))
        self.ReadGestureButton.setText(_translate("MainWindow", "Read"))
        self.GestureName.setText(_translate("MainWindow", "Name"))
        self.label_7.setText(_translate("MainWindow", "Function:"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.label_8.setText(_translate("MainWindow", "Combo: "))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.label_9.setText(_translate("MainWindow", "Status:"))
        self.StatusLabel.setText(_translate("MainWindow", "Idle"))
        self.ComboLabel.setText(_translate("MainWindow", "None"))
        self.label_10.setText(_translate("MainWindow", "Saved Gestures"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabGestures), _translate("MainWindow", "Gestures"))
        self.TalkButton.setText(_translate("MainWindow", "Talk"))
        self.VoiceLabel.setText(_translate("MainWindow", "Hi! I\'m your virtual assistant."))
        self.label_2.setText(_translate("MainWindow", "Google News"))
        self.label_3.setText(_translate("MainWindow", "YouTube"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.label_6.setText(_translate("MainWindow", "Reminder"))
        self.label_4.setText(_translate("MainWindow", "Statistics"))
        self.label_11.setText(_translate("MainWindow", "News"))
        self.label_12.setText(_translate("MainWindow", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabVA), _translate("MainWindow", "Virtual Assistant"))

